
; ---- ADC #
    ORG $6900
    FETCH TMP4
    ADC8 ALO TMP4 CFLAG
    BRACCU16 ADC_#_16bit
    NEXT
ADC_#_16bit:    
    FETCH TMP4
    ADC8 AHI TMP4 CFLAG
    COMPUTEZFLAG ALO AHI
    NEXT

; ---- ADC d
    ORG $6500
    FETCHADDRESS_d TMP4 TMP5
    LOAD TMP4 TMP5 V0 TMP3
    ADC8 ALO TMP3 CFLAG
    BRACCU16 ADC_d_16bit
    NEXT
ADC_d_16bit:    
    INC16 TMP4 TMP5
    LOAD TMP4 TMP5 V0 TMP3
    ADC8 AHI TMP3 CFLAG
    COMPUTEZFLAG ALO AHI
    NEXT
    
