
; ---- JMP a
    ORG $4C00
    FETCH TMP2
    FETCH TMP3
    COPY16 PCLO PCHI TMP2 TMP3
    NEXT

; ---- JMP al
    ORG $5C00
    FETCH TMP2
    FETCH TMP3
    LOAD PCLO PCHI PBR PBR
    COPY16 PCLO PCHI TMP2 TMP3
    NEXT

; ---- JMP (a)
    ORG $6C00
    FETCH TMP2
    FETCH TMP3    
    LOAD_POSTINC TMP2 TMP3 V0 PCLO
    LOAD TMP2 TMP3 V0 PCHI
    NEXT
    
; ---- JMP (a,x)
    ORG $7C00
    FETCH TMP2
    FETCH TMP3    
    ADD16 TMP2 TMP3 XLO XHI
    LOAD_POSTINC TMP2 TMP3 V0 PCLO
    LOAD TMP2 TMP3 V0 PCHI
    NEXT
    