; MODES: a  a,x  a,y  al  al,x  d  d,s  d,x  (d>  [d]  (d,s),y  (d,y)  (d),y  [d],y  #

; ---- LDA a
    ORG $AD00
    FETCHADDRESS_a TMP2 TMP3
    LOAD TMP2 TMP3 DBR ALO
    BRACCU16 LDA_a_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_a_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 DBR AHI
    COMPUTENZFLAGS ALO AHI
    NEXT
    
; ---- LDA a,x
    ORG $BD00
    FETCHADDRESS_a_x TMP2 TMP3
    LOAD TMP2 TMP3 DBR ALO
    BRACCU16 LDA_a_x_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_a_x_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 DBR AHI
    COMPUTENZFLAGS ALO AHI
    NEXT

; ---- LDA al
    ORG $AF00
    FETCHADDRESS_al TMP2 TMP3 TMP4
    LOAD TMP2 TMP3 TMP4 ALO
    BRACCU16 LDA_al_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_al_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 TMP4 AHI
    COMPUTENZFLAGS ALO AHI
    NEXT

; ---- LDA al,x
    ORG $BF00
    FETCHADDRESS_al_x TMP2 TMP3 TMP4
    LOAD TMP2 TMP3 TMP4 ALO
    BRACCU16 LDA_alx_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_alx_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 TMP4 AHI
    COMPUTENZFLAGS ALO AHI
    NEXT
        
; ---- LDA d
    ORG $A500
    FETCHADDRESS_d TMP2 TMP3
    LOAD TMP2 TMP3 V0 ALO
    BRACCU16 LDA_d_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_d_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 V0 AHI
    COMPUTENZFLAGS ALO AHI
    NEXT

; ---- LDA [d]
    ORG $A700
    FETCHADDRESS_[d] TMP2 TMP3 TMP4
    LOAD TMP2 TMP3 TMP4 ALO
    BRACCU16 LDA_[d]_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_[d]_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 TMP4 AHI
    COMPUTENZFLAGS ALO AHI
    NEXT
    
    ; ---- LDA d,s
    ORG $A300
    FETCHADDRESS_d_s TMP2 TMP3
    LOAD TMP2 TMP3 V0 ALO
    BRACCU16 LDA_d_s_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_d_s_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 V0 AHI
    COMPUTENZFLAGS ALO AHI
    NEXT
    
; ---- LDA #
    ORG $A900
    FETCH ALO
    BRACCU16 LDA_#_16bit
    GET ALO
    SET ZFLAG
    SET NFLAG
    NEXT
LDA_#_16bit:
    FETCH AHI
    COMPUTENZFLAGS ALO AHI
    NEXT

    
    
