
; ---- LDX #
    ORG $A200
    FETCH XLO
    BRINDEX16 LDX_#_16bit
    GET XLO
    SET NFLAG
    SET ZFLAG
    NEXT
LDX_#_16bit:    
    FETCH XHI
    COMPUTENZFLAGS XLO XHI
    NEXT

; ---- LDX a
    ORG $AE00
    FETCHADDRESS_a TMP2 TMP3
    LOAD TMP2 TMP3 DBR XLO
    BRINDEX16 LDX_a_16bit
    GET XLO
    SET ZFLAG
    SET NFLAG
    NEXT
LDX_a_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 DBR XHI
    COMPUTENZFLAGS XLO XHI
    NEXT
