
; ---- LDX #
    ORG $A200
    FETCH XLO
    BRINDEX16 LDX_#_16bit
    NZ8 XLO
    NEXT
LDX_#_16bit:    
    FETCH XHI
    NZ16 XLO XHI
    NEXT

; ---- LDX a
    ORG $AE00
    FETCHADDRESS_a TMP2 TMP3
    LOAD TMP2 TMP3 DBR XLO
    BRINDEX16 LDX_a_16bit
    NZ8 XLO
    NEXT
LDX_a_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 DBR XHI
    NZ16 XLO XHI
    NEXT

; ---- LDX d
    ORG $A600
    FETCHADDRESS_d TMP2 TMP3
    LOAD TMP2 TMP3 V0 XLO
    BRINDEX16 LDX_d_16bit
    NZ8 XLO
    NEXT
LDX_d_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 V0 XHI
    NZ16 XLO XHI
    NEXT
