
; ---- LDY #
    ORG $A000
    FETCH YLO
    BRINDEX16 LDY_#_16bit
    GET YLO
    SET NFLAG
    SET ZFLAG
    NEXT
LDY_#_16bit:    
    FETCH YHI
    COMPUTENZFLAGS XLO XHI
    NEXT

; ---- LDY a
    ORG $AC00
    FETCHADDRESS_a TMP2 TMP3
    LOAD TMP2 TMP3 DBR YLO
    BRINDEX16 LDY_a_16bit
    GET YLO
    SET ZFLAG
    SET NFLAG
    NEXT
LDY_a_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 DBR YHI
    COMPUTENZFLAGS XLO YHI
    NEXT
    
    ; ---- LDY d
    ORG $A400
    FETCHADDRESS_d TMP2 TMP3
    LOAD TMP2 TMP3 V0 YLO
    BRINDEX16 LDY_d_16bit
    GET YLO
    SET ZFLAG
    SET NFLAG
    NEXT
LDY_d_16bit:    
    INC16 TMP2 TMP3
    LOAD TMP2 TMP3 V0 YHI
    COMPUTENZFLAGS YLO YHI
    NEXT
