; ---- STA d
    ORG $8500
    FETCHADDRESS_d
    STORE V0 ALO
    BRACCU16 STA_d_16bit
    NEXT
STA_d_16bit:    
    INCREMENTADDRESS
    STORE V0 AHI
    NEXT

; ---- STA d,s
    ORG $8300
    FETCHADDRESS_d_s
    STORE V0 ALO
    BRACCU16 STA_d_s_16bit
    NEXT
STA_d_s_16bit:    
    INCREMENTADDRESS
    STORE V0 AHI
    NEXT
    
; ---- STA a
    ORG $8D00
    FETCHADDRESS_a
    STORE DBR ALO
    BRACCU16 STA_a_16bit
    NEXT
STA_a_16bit:    
    INCREMENTADDRESS
    STORE DBR AHI
    NEXT

; ---- STA al
    ORG $8F00
    FETCHADDRESS_a
    FETCH TMP4
    STORE TMP4 ALO
    BRACCU16 STA_al_16bit
    NEXT
STA_al_16bit:    
    INCREMENTADDRESS
    STORE TMP4 AHI
    NEXT

; ---- STA al,x
    ORG $9F00
    FETCHADDRESS_a_x
    FETCH TMP4
    STORE TMP4 ALO
    BRACCU16 STA_al_x_16bit
    NEXT
STA_al_x_16bit:    
    INCREMENTADDRESS
    STORE TMP4 AHI
    NEXT

; ---- STA [d]
    ORG $8700
    FETCHADDRESS_[d] TMP4
    STORE TMP4 ALO
    BRACCU16 STA_[d]_16bit
    NEXT
STA_[d]_16bit:    
    INCREMENTADDRESS
    STORE TMP4 AHI
    NEXT
