; ---- TAX i
    ORG $AA00
    BRINDEX16 TAX_to16
; to 8
    GET ALO
    SET XLO
    SET NFLAG
    SET ZFLAG
    NEXT
TAX_to16:
    BRACCU16 TAX_16to16
; 8 to 16
    COPY16 XLO XHI ALO V0
    COMPUTENZFLAGS XLO XHI
    NEXT
TAX_16to16:
    COPY16 XLO XHI ALO AHI
    COMPUTENZFLAGS XLO XHI
    NEXT
    