; ---- TAY i
    ORG $A800
    BRINDEX16 TAY_to16
; to 8
    GET ALO
    SET YLO
    SET NFLAG
    SET ZFLAG
    NEXT
TAY_to16:
    BRACCU16 TAY_16to16
; 8 to 16
    COPY16 YLO YHI ALO V0
    COMPUTENZFLAGS YLO YHI
    NEXT
TAY_16to16:
    COPY16 YLO YHI ALO AHI
    COMPUTENZFLAGS YLO YHI
    NEXT
