; ---- TXA i
    ORG $8A00
    BRACCU16 TXA_to16
; to 8
    GET XLO
    SET ALO
    SET NFLAG
    SET ZFLAG
    NEXT
TXA_to16:
    BRINDEX16 TXA_16to16
; 8 to 16
    COPY16 ALO AHI XLO V0
    COMPUTENZFLAGS ALO AHI
    NEXT
TXA_16to16:
    COPY16 ALO AHI XLO XHI 
    COMPUTENZFLAGS ALO AHI
    NEXT
